### ISSUE TITLE
Broken method risc0_zkvm::guest::sha::digest

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-rust-examples#48]
Based on the test results from this PR https://github.com/risc0/risc0-rust-examples/pull/45 (CI run: https://github.com/risc0/risc0-rust-examples/actions/runs/4028293123/jobs/6925018354), the `risc0_zkvm::guest::sha::digest` appears to be broken. I confirmed this and was able to work around it by using a different method, but this one should be fixed (or removed)

**Comment by nategraf** [comment]
Realized I posted this to the wrong repo. Superseded by https://github.com/risc0/risc0/issues/356

**Comment by tzerrell** [comment]
:+1: We also want the SHA example working in this repo but #45 is still WIP and we'll track this as part of getting tests passing for it.
