### ISSUE TITLE
waldo failing to prove

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0-rust-examples#53]
The first instruction from the `waldo` readme is failing on my M1 Macbook Air.

![image](https://user-images.githubusercontent.com/15272444/220773430-8e6ac0c3-0fb4-4356-958b-d3a4150a74d7.png)

**Comment by pdg744** [comment]
Maybe I don't have enough memory on this machine?

**Comment by flaub** [comment]
In my testing, this consumed around 64GB of RAM, so I suspect that the failure is really an out of memory condition.

**Comment by js4ngu** [comment]
@WSL2 Ubunt

In The Host is equipped with 32gb.
WSL2 can use 16GB of mem.

Looking at the htop command, it seems that 16GB is almost used for peak.
![image](https://user-images.githubusercontent.com/30527114/220824180-8ca26593-47ee-46dc-b8e3-c11e953b63a3.png)

**Comment by js4ngu** [comment]
![image](https://user-images.githubusercontent.com/30527114/220833453-9f681804-491c-4218-a17d-fdf9751f1729.png)
![image](https://user-images.githubusercontent.com/30527114/220833485-19299a04-c9ab-4914-af14-226e94fb02fd.png)

I allocated 54 gigabytes of virtual memory.
And yet the same problem arises.
I think there's a problem.

**Comment by js4ngu** [comment]
Swap memory has been allocated to 128 gigabytes.

After, I command it in my bash
```RUST_LOG=debug cargo run --release --bin prove -- -i waldo.webp -x 1150 -y 291 -w 58 -h 70 -m waldo_mask.png```

There has been no response for almost an hour since the last debug message.
The memory share is also a bit strange.

The CPU of HOSTpc is i7-9700k.

![image](https://user-images.githubusercontent.com/30527114/220848752-0a33891d-0584-4d3f-ac18-5fbba195968d.png)

**Comment by js4ngu** [comment]
Prover build Success! It took 67 minutes.

HOST CPU : i7-9700k
HOST RAM : 32Gb

WSL alloc RAM : 16Gb
WSL alloc swpRAM : 128Gb (SSD)
![image](https://user-images.githubusercontent.com/30527114/220859952-a5d389c1-5f85-49b4-aa03-ef7ebf1a08b5.png)

**Comment by tzerrell** [comment]
Glad this is working! We've added a warning about memory.
